//-----------------------------------------------------------------------
// <copyright file="Parser.cs" company="Andy Young">
//     Copyright (c) Andy Young. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated /> from http://jsonutils.com/
namespace TuneGenieParser
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public class Meta
    {
        [JsonProperty("status")]
        public int Status { get; set; }

        [JsonProperty("base_url")]
        public string BaseUrl { get; set; }
    }

    public class Response
    {
        [JsonProperty("artistlink")]
        public string Artistlink { get; set; }

        [JsonProperty("sid")]
        public int Sid { get; set; }

        [JsonProperty("played_at_display")]
        public string PlayedAtDisplay { get; set; }

        [JsonProperty("sslg")]
        public string Sslg { get; set; }

        [JsonProperty("songlink")]
        public string Songlink { get; set; }

        [JsonProperty("concertslink")]
        public string Concertslink { get; set; }

        [JsonProperty("played_at")]
        public DateTime PlayedAt { get; set; }

        [JsonProperty("albumslink")]
        public string Albumslink { get; set; }

        [JsonProperty("artist")]
        public string Artist { get; set; }

        [JsonProperty("song")]
        public string Song { get; set; }

        [JsonProperty("videolink")]
        public string Videolink { get; set; }

        [JsonProperty("aslg")]
        public string Aslg { get; set; }

        [JsonProperty("lyriclink")]
        public string Lyriclink { get; set; }

        [JsonProperty("topttrackslink")]
        public string Topttrackslink { get; set; }

        public override string ToString()
        {
            return string.Format("{0} - {1}", this.Artist, this.Song);
        }
    }

    public class NowPlaying
    {
        [JsonProperty("meta")]
        public Meta Meta { get; set; }

        [JsonProperty("response")]
        public List<Response> Response { get; set; }
    }
}
